services:
  db:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    networks:
      - family_budget_network_dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: family-budget-dev
      ENVIRONMENT: dev
    networks:
      - family_budget_network_dev

volumes:
  postgres_data_dev:

networks:
  family_budget_network_dev:
    driver: bridge