"""add admin role

Revision ID: c13cd3baab00
Revises: fb443f212f20
Create Date: 2026-02-21 17:56:19.111365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c13cd3baab00'
down_revision: Union[str, Sequence[str], None] = 'fb443f212f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'families', 'users', ['admin_id'], ['id'])
    op.alter_column('transactions', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.alter_column('users', 'family_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('users_family_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'families', ['family_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_family_id_fkey'), 'users', 'families', ['family_id'], ['id'])
    op.alter_column('users', 'family_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.alter_column('transactions', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_column('families', 'admin_id')
    # ### end Alembic commands ###
